#!/usr/bin/env python3
"""
Regenerate the Claude Design bundle from app-preview.html.

The previews used to duplicate the app's CSS by hand, which meant editing the
app silently made the design system wrong. This pulls the real rules out of
app-preview.html instead, so a card can only ever show what the app actually
does.

    python3 scripts/build-design-system.py [--out DIR] [--check]

--check exits non-zero if the bundle on disk differs from what would be
generated, which is what the hook uses to decide whether a re-push is owed.
"""

import argparse, base64, io, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "app-preview.html")


# ---------------------------------------------------------------- css parsing
def style_block(html):
    """The first <style> block: the app's own stylesheet.

    The second one holds the base64 photographs and is deliberately skipped -
    a component library should show the component, not ship a photo library.
    """
    a = html.index("<style>") + len("<style>")
    return html[a : html.index("</style>", a)]


def top_level_rules(css):
    """Yield (selector, body) for each top-level rule.

    Brace-counting rather than a regex, because the sheet contains @media,
    @supports and @keyframes blocks whose nested rules must not be mistaken
    for top-level ones.
    """
    out, i, n = [], 0, len(css)
    while i < n:
        b = css.find("{", i)
        if b == -1:
            break
        # a top-level statement such as `@import url(...);` sits in front of the
        # next selector, so keep only what follows the last `;`
        sel = css[i:b].split(";")[-1].strip()
        depth, j = 1, b + 1
        while j < n and depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        body = css[b + 1 : j - 1]
        if sel and not sel.startswith("@"):
            out.append((sel, body.strip()))
        i = j
    return out


def rules_for(css, wanted):
    """Every top-level rule whose selector list touches one of `wanted`.

    Matches on the bare class token so `.pw` picks up `.pw::after` and
    `.poster:hover .pw`, but never `.pwx`.
    """
    keep = []
    for sel, body in top_level_rules(css):
        parts = [p.strip() for p in sel.split(",")]
        hit = False
        for p in parts:
            for w in wanted:
                if re.search(r"(?<![\w-])" + re.escape(w) + r"(?![\w-])", p):
                    hit = True
                    break
            if hit:
                break
        if hit:
            keep.append(sel + "{" + body + "}")
    return "\n".join(keep)


def tokens(css):
    for sel, body in top_level_rules(css):
        if sel == ":root":
            return ":root{" + body + "}"
    raise SystemExit("no :root token block found in app-preview.html")


# ------------------------------------------------------------------ card shell
BASE = """
*{box-sizing:border-box}
body{margin:0;padding:22px;background:var(--bg);color:var(--text);
  font-family:Manrope,"Noto Sans KR",-apple-system,BlinkMacSystemFont,sans-serif}
button{font-family:inherit;cursor:pointer}
.ds-h{margin:0 0 4px;font-size:.78rem;font-weight:800;letter-spacing:.04em;
  text-transform:uppercase;color:var(--text-2)}
.ds-note{margin:0 0 16px;font-size:.82rem;color:var(--text-2);line-height:1.5;max-width:60ch}
.ds-row{display:flex;gap:12px;flex-wrap:wrap;align-items:flex-start}
.ic{width:22px;height:22px;stroke:currentColor;fill:none;stroke-width:2.5;
  stroke-linecap:round;stroke-linejoin:round;flex-shrink:0}
.ic-s{width:16px;height:16px}
"""

GEN = "<!-- generated by scripts/build-design-system.py - edit the app, not this file -->"


def card(group, title, note, body, css, extra=""):
    return (
        '<!-- @dsCard group="%s" -->\n%s\n' % (group, GEN)
        + '<!doctype html><html><head><meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        "<title>" + title + "</title>\n<style>\n" + css + "\n" + BASE + "\n" + extra
        + "</style></head><body>\n"
        '<p class="ds-h">' + title + "</p>\n"
        '<p class="ds-note">' + note + "</p>\n" + body + "\n</body></html>\n"
    )


def photo(name, px=300, q=55):
    """A hard-downscaled still, only for cards that are meaningless without one."""
    src = os.path.join(ROOT, "..", "img", name)
    tmp = "/tmp/_ds_%s" % name
    for cand in (src, os.path.join(ROOT, "img", name)):
        if os.path.exists(cand):
            subprocess.run(
                ["sips", "-Z", str(px), "--setProperty", "formatOptions", str(q),
                 cand, "--out", tmp],
                capture_output=True,
            )
            if os.path.exists(tmp):
                d = open(tmp, "rb").read()
                os.remove(tmp)
                return "data:image/jpeg;base64," + base64.b64encode(d).decode()
    return ""  # missing photo degrades to the gradient bed underneath


# ------------------------------------------------------------------ the cards
def build(css, imgs):
    T = tokens(css)
    R = lambda *sel: rules_for(css, list(sel))
    C = {}

    # -- Foundations -------------------------------------------------------
    swatches = [
        ("brand", "Fills and large glyphs. Never small text."),
        ("brand-ink", "5.4:1 - safe for small text."),
        ("brand-btn", "White on this = 4.6:1."),
        ("brand-tint", "Quiet backgrounds and rings."),
        ("text", "Body. 15.9:1."),
        ("text-2", "Secondary. 7.0:1."),
        ("line", "Dividers only, never an image edge."),
        ("ok", "Verified, paid, available."),
        ("warn", "Overdue, needs attention."),
    ]
    vals = dict(re.findall(r"--([\w-]+):\s*([^;]+);", T))
    C["foundations/colors.html"] = card(
        "Foundations", "Colour",
        "White ground, one rose accent. Three accent steps exist so contrast is "
        "never guessed: fills, small text and buttons each get their own.",
        '<div class="ds-row">'
        + "".join(
            '<div style="flex:0 0 132px">'
            '<div style="height:60px;border-radius:12px;background:var(--%s);'
            'border:1px solid rgba(0,0,0,.08)"></div>'
            '<p style="margin:7px 0 0;font-size:.8rem;font-weight:800">%s</p>'
            '<p style="margin:1px 0 0;font-size:.72rem;color:var(--text-2);'
            'font-family:ui-monospace,monospace">%s</p>'
            '<p style="margin:3px 0 0;font-size:.7rem;color:var(--text-2);'
            'line-height:1.4">%s</p></div>' % (n, n, vals.get(n, "").strip(), note)
            for n, note in swatches
        )
        + "</div>", T)

    C["foundations/type.html"] = card(
        "Foundations", "Type scale",
        "Manrope with Noto Sans KR for Korean. Weights run heavy: 700 is the floor "
        "for anything that labels something, 800 for headings.",
        "".join(
            '<div style="margin-bottom:14px"><span style="%s">%s</span>'
            '<span style="margin-left:12px;font-size:.75rem;color:var(--text-2)">%s</span></div>'
            % (s, sample, label)
            for s, sample, label in [
                ("font-size:3rem;font-weight:800;letter-spacing:-.03em", "412", "Hero figure &middot; 3rem/800"),
                ("font-size:1.92rem;font-weight:800;letter-spacing:-.03em", "Maple Grove", "Hero title &middot; 1.92rem/800"),
                ("font-size:1.62rem;font-weight:800;letter-spacing:-.02em", "Browse", "Screen title &middot; 1.62rem/800"),
                ("font-size:1.12rem;font-weight:800", "Trusted near you", "Section &middot; 1.12rem/800"),
                ("font-size:1rem;font-weight:500", "Body copy sits at 1rem and never below.", "Body &middot; 1rem/500"),
                ("font-size:.86rem;font-weight:700;color:var(--text-2)", "&#9733; 4.9 (38) &middot; Rentals", "Meta &middot; .86rem/700"),
                ("font-size:1.5rem;font-weight:800", "믿을 수 있는 업체", "Korean &middot; same scale"),
            ]
        ), T)

    C["foundations/spacing.html"] = card(
        "Foundations", "Spacing and radii",
        "Radii are concentric: an inner corner plus its inset equals the outer "
        "corner. Touch targets default to 52px because the audience skews older.",
        '<div class="ds-row" style="align-items:flex-end">'
        + "".join(
            '<div style="text-align:center"><div style="width:%dpx;height:%dpx;'
            'background:var(--brand-tint);border:1px solid var(--brand);border-radius:%s"></div>'
            '<p style="margin:6px 0 0;font-size:.74rem;font-weight:800">%s</p></div>'
            % (w, w, r, l)
            for w, r, l in [(14, "var(--r)", "--r"), (22, "var(--r-lg)", "--r-lg"),
                            (26, "var(--r-sheet)", "--r-sheet"), (28, "28px", "island"),
                            (44, "999px", "pill")]
        )
        + "</div>"
        '<p class="ds-note" style="margin-top:20px">Touch targets: 52px default, '
        "44px for secondary, 24px is the absolute WCAG floor and is used only for "
        "carousel dots.</p>"
        '<div class="ds-row">'
        '<div style="width:var(--tap);height:var(--tap);border-radius:var(--r);background:var(--brand-btn)"></div>'
        '<div style="width:44px;height:44px;border-radius:var(--r);background:var(--text-2)"></div>'
        '<div style="width:24px;height:24px;border-radius:8px;background:var(--line)"></div>'
        "</div>", T)

    # -- Cards -------------------------------------------------------------
    def poster(img, flag, price, name, meta):
        return ('<button class="poster" style="width:138px"><div class="pw" '
                'style="background-image:url(%s);background-size:cover;background-position:center">'
                "%s" '<div class="pt"><p class="pp">%s</p><p class="pn">%s</p></div></div>'
                '<p class="pmeta">%s</p></button>' % (img, flag, price, name, meta))

    C["components/poster.html"] = card(
        "Cards", "Poster",
        "The primary listing unit. 2:3 artwork, title and price over a bottom "
        "scrim, meta below the frame. Hover outlines in brand and lifts; press "
        "scales to 0.96.",
        '<div class="ds-row">'
        + poster(imgs["home"], '<span class="flag">Free today</span>',
                 "$800-1,800/mo", "Maple Grove Property Group", "&#9733; 4.9 &middot; Rentals")
        + poster(imgs["clean"], '<span class="flag">Free today</span>',
                 "$100-220", "Sparkle Home Services", "&#9733; 4.7 &middot; Cleaning")
        + poster(imgs["clinic"], "", "Covered by AHCIP",
                 "Bow River Family Clinic", "&#9733; 4.9 &middot; Clinic")
        + "</div>",
        T + "\n" + R(".poster", ".pw", ".flag", ".pt", ".pp", ".pn", ".pmeta", ".art"))

    C["components/hero.html"] = card(
        "Cards", "Hero slide",
        "Full-bleed photo with a white scrim carrying the headline. The scrim "
        "reaches 0.93 opacity behind text, so the headline stays legible over any "
        "photograph, dark or light.",
        '<div class="hero" style="width:360px;max-width:100%">'
        '<div class="hw" style="background-image:url(' + imgs["home"] + ');'
        'background-size:cover;background-position:center;border-radius:16px">'
        '<div class="hb"><span class="hflag">Featured now</span>'
        "<h2>Maple Grove Property Group</h2>"
        '<p class="hm">&#9733; 4.9 (38) &middot; Rentals &middot; NW Calgary</p>'
        '<p class="hd">Furnished rooms and townhouses near downtown. '
        "Bilingual leasing agent.</p>"
        '<span class="hcue">See details</span></div></div></div>'
        '<div class="herodots" style="width:360px">'
        + "".join('<button class="hdot"%s><i></i></button>'
                  % (' aria-current="true"' if i == 0 else "") for i in range(5))
        + "</div>",
        T + "\n" + R(".hero", ".hw", ".hb", ".hflag", ".hcue", ".herodots", ".hdot", ".art"))

    # -- Navigation --------------------------------------------------------
    ICONS = {
        "home": '<path d="M4 11l8-7.5L20 11"/><path d="M6 10v10.5h5.2V15h1.6v5.5H18V10"/>',
        "grid": '<rect x="3" y="3" width="7.5" height="7.5" rx="2"/><rect x="13.5" y="3" width="7.5" height="7.5" rx="2"/><rect x="3" y="13.5" width="7.5" height="7.5" rx="2"/><rect x="13.5" y="13.5" width="7.5" height="7.5" rx="2"/>',
        "group": '<circle cx="9" cy="8.4" r="3.3"/><path d="M2.6 19.6c0-3.3 2.9-5.5 6.4-5.5s6.4 2.2 6.4 5.5"/><path d="M16.2 5.6a3.3 3.3 0 010 6.4M17.6 14.6c2.4.6 3.9 2.4 3.9 5"/>',
        "heart": '<path d="M12 20.3s-7.2-4.4-9.5-8.9C1.1 7.9 2.7 4.8 6.2 4.8c2 0 3.4 1 4.1 2.3.7-1.3 2.1-2.3 4.1-2.3 3.5 0 5.1 3.1 3.7 6.6-2.3 4.5-9.5 8.9-9.5 8.9z"/>',
        "inbox": '<path d="M4 5.5h16v13H4z"/><path d="M4 13.5h5l1.3 2.3h3.4L15 13.5h5"/>',
        "user": '<circle cx="12" cy="8.5" r="3.6"/><path d="M4.5 20c0-3.6 3.2-6 7.5-6s7.5 2.4 7.5 6"/>',
        "mic": '<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0014 0M12 18v3"/>',
        "search": '<circle cx="10.5" cy="10.5" r="6.5"/><path d="M20 20l-5-5"/>',
    }
    ic = lambda n, c="": '<svg class="ic %s" viewBox="0 0 24 24">%s</svg>' % (c, ICONS[n])

    C["components/tabbar.html"] = card(
        "Navigation", "Island toolbar",
        "The whole control deck floats: inset from the edges, 28px corners, "
        "translucent with a backdrop blur, and content scrolls underneath it. "
        "Search, the language control and all six tabs sit inside one island. Language "
        "is a primary control for this audience, not a setting buried in a profile screen.",
        '<div class="deck" style="position:relative;left:auto;right:auto;bottom:auto;'
        'width:360px;max-width:100%">'
        '<div class="searchdock">' + ic("search") +
        '<input placeholder="What do you need?">'
        '<button class="langbtn">EN</button>'
        '<button class="voicebtn">' + ic("mic") + "</button></div>"
        '<nav class="tabs">'
        + "".join('<button class="tab%s">%s<span>%s</span></button>'
                  % (" on" if lbl == "Home" else "", ic(i), lbl)
                  for lbl, i in [("Home", "home"), ("Browse", "grid"),
                                 ("Community", "group"), ("Saved", "heart"),
                                 ("Inbox", "inbox"), ("You", "user")])
        + "</nav></div>",
        T + "\n" + R(".deck", ".searchdock", ".langbtn", ".voicebtn", ".tabs", ".tab", ".vicon", ".vmic", ".vstop"),
        "body{background:#e9eaec}")

    # -- Messaging ---------------------------------------------------------
    C["components/bubbles.html"] = card(
        "Messaging", "Conversation bubbles",
        "Grouped the way iOS groups them: a tail appears only on the last bubble "
        "of a run, and the delivery stamp only under your last sent message.",
        '<div style="width:340px;max-width:100%;display:flex;flex-direction:column;gap:2px">'
        '<div class="chat-time">Today</div>'
        '<div class="bub me tail-me">Hi, I need a move-out clean. Two bedroom, before Friday.</div>'
        '<div class="chat-status">Delivered &middot; 9:02 AM</div>'
        '<div class="bub them">We can do Friday at 11:30am. Flat rate $180, about three hours.</div>'
        '<div class="bub them tail-them">Do you need the oven and fridge done as well?</div>'
        '<div class="chat-stamp">9:06 AM</div>'
        '<div class="bub them typing"><i></i><i></i><i></i></div></div>',
        T + "\n" + R(".bub", ".chat-time", ".chat-status", ".chat-stamp")
        + "\n@keyframes tp{0%,60%,100%{opacity:.35;transform:translateY(0)}"
          "30%{opacity:1;transform:translateY(-3px)}}"
          "@media (prefers-reduced-motion:reduce){*{animation:none!important}}")

    C["components/island.html"] = card(
        "Messaging", "Notification island",
        "Floats above the search bar rather than at the top of the screen, so a "
        "notification lands in the same thumb zone as every other control.",
        '<div class="island on" style="position:relative;bottom:auto;left:auto;right:auto;'
        'margin:0;width:352px;max-width:100%">'
        '<span class="iav" style="background:linear-gradient(160deg,#d6f2e8 8%,#94d3bd 92%)"></span>'
        '<span class="ibd"><p class="it">Sparkle Home Services</p>'
        '<p class="im">Accepted your request. Friday 11:30am works.</p></span>'
        '<span class="ix"><svg class="ic ic-s" viewBox="0 0 24 24">'
        '<path d="M6 6l12 12M18 6L6 18"/></svg></span></div>',
        T + "\n" + R(".island", ".iav", ".ibd", ".it", ".im", ".ix"),
        "body{background:#e9eaec}")

    # -- Trust -------------------------------------------------------------
    BADGES = [("ok", "id", "ID verified"), ("b", "brief", "Business verified"),
              ("b", "shield", "Licensed"), ("ok", "shield", "Insured"),
              ("b", "shield", "Payment protected"), ("n", "user", "New member"),
              ("w", "star", "Top rated"), ("off", "help", "Not verified yet")]
    BI = {"id": '<rect x="3" y="5" width="18" height="14" rx="3"/><circle cx="9" cy="11" r="2.1"/><path d="M6 16c0-2 1.5-3.1 3-3.1s3 1.1 3 3.1M14.3 9.3h4.2M14.3 13.1h4.2"/>',
          "brief": '<rect x="3" y="7.5" width="18" height="12" rx="2"/><path d="M8.5 7.5V6a2 2 0 012-2h3a2 2 0 012 2v1.5M3 13h18"/>',
          "shield": '<path d="M12 3l7 3.2v5.6c0 5-3.3 7.8-7 9-3.7-1.2-7-4-7-9V6.2L12 3z"/><path d="M9 12.2l2.2 2.2L15.5 10"/>',
          "user": ICONS["user"],
          "star": '<polygon points="12,3.2 14.7,9.3 21.3,10 16.4,14.4 17.8,21 12,17.6 6.2,21 7.6,14.4 2.7,10 9.3,9.3"/>',
          "help": '<circle cx="12" cy="12" r="9"/><path d="M9.5 9.2a2.6 2.6 0 015 .9c0 1.7-2.5 2.2-2.5 4M12 17.2v.2"/>'}
    C["components/badges.html"] = card(
        "Trust", "Verification badges",
        "One vocabulary shared by people and businesses, so a badge means the same "
        "thing wherever it appears. Each pairs an icon with a label, never colour alone.",
        '<div class="ds-row">'
        + "".join('<span class="vb %s"><svg class="ic ic-s" viewBox="0 0 24 24">%s</svg>%s</span>'
                  % (c, BI[i], l) for c, i, l in BADGES)
        + "</div>", T + "\n" + R(".vb"))

    C["components/review.html"] = card(
        "Trust", "Review block",
        "A star average with no words behind it is the thinnest trust signal a "
        "marketplace can have. Every listing carries written reviews.",
        '<div style="width:340px;max-width:100%">'
        '<p style="margin:0 0 2px;font-size:.85rem;font-weight:800">What people say</p>'
        '<p style="margin:0;font-size:.86rem;color:var(--text-2);font-weight:700">'
        "&#9733; 4.7 &middot; 21 reviews</p>"
        '<div class="rev"><div class="rev-top"><span class="rev-n">Daniel N.</span>'
        '<span class="rev-s">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
        '<span class="rev-d">5 days ago</span></div>'
        '<p class="rev-x">Move-out clean got our whole deposit back. They did the oven '
        "without being asked.</p></div>"
        '<div class="rev"><div class="rev-top"><span class="rev-n">Priya S.</span>'
        '<span class="rev-s">&#9733;&#9733;&#9733;&#9733;</span>'
        '<span class="rev-d">3 weeks ago</span></div>'
        '<p class="rev-x">Good work, arrived twenty minutes late but called ahead.</p>'
        "</div></div>", T + "\n" + R(".rev"))

    # -- Data --------------------------------------------------------------
    C["components/stats.html"] = card(
        "Data", "Stat tiles and hero figure",
        "One hero figure per view, never more. Proportional figures on large "
        "numbers; tabular figures are reserved for columns that must align.",
        '<div style="width:340px;max-width:100%">'
        '<div class="hero-fig"><p class="hl">Profile visits this week</p>'
        '<p class="hv">412</p><p class="hd up">+17% vs last week</p></div>'
        '<div class="tiles">'
        '<div class="tile"><p class="tl">New requests</p><p class="tv">3</p></div>'
        '<div class="tile"><p class="tl">Jobs booked</p><p class="tv">9</p></div>'
        '<div class="tile"><p class="tl">Paid out</p><p class="tv">$1,840</p></div>'
        "</div></div>", T + "\n" + R(".hero-fig", ".tiles", ".tile"))

    bars, days = [38, 52, 41, 66, 73, 58, 84], ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    W, H, top = 335, 132, 100
    band, bw = W / len(bars), 24
    gap = (band - bw) / 2
    sv = []
    for i, v in enumerate(bars):
        h = max(3, round(v / top * (H - 26)))
        x = round(i * band + gap)
        sv.append('<rect x="%d" y="%d" width="%d" height="%d" rx="4" ry="4" fill="var(--brand-btn)"/>'
                  % (x, H - 18 - h, bw, h))
        sv.append('<rect x="%d" y="%d" width="%d" height="4" fill="var(--brand-btn)"/>'
                  % (x, H - 22, bw))
    for i, d in enumerate(days):
        sv.append('<text x="%d" y="%d" text-anchor="middle" font-size="10" font-weight="700" '
                  'fill="var(--text-2)">%s</text>' % (round(i * band + band / 2), H - 4, d))
    pk = bars.index(max(bars))
    ph = round(max(bars) / top * (H - 26))
    sv.append('<text x="%d" y="%d" text-anchor="middle" font-size="11" font-weight="800" '
              'fill="var(--text)">%d</text>' % (round(pk * band + band / 2), H - 24 - ph, max(bars)))
    C["components/chart.html"] = card(
        "Data", "Column chart",
        "Single series, so one hue for every column and no legend - the heading "
        "names what is plotted. Columns cap at 24px with a rounded data-end and a "
        "square baseline. Only the peak is labelled; the rest live in the tooltip.",
        '<div style="width:335px;max-width:100%%">'
        '<h4 style="margin:0 0 2px;font-size:1rem;font-weight:800">Visits per day</h4>'
        '<p style="margin:0 0 10px;font-size:.8rem;color:var(--text-2)">'
        "Last 7 days, Monday to Sunday</p>"
        '<svg viewBox="0 0 %d %d" width="100%%" height="%d" role="img" '
        'aria-label="Visits per day: %s">'
        '<line x1="0" y1="%d" x2="%d" y2="%d" stroke="var(--line)" stroke-width="1"/>'
        '<line x1="0" y1="%d" x2="%d" y2="%d" stroke="var(--line)" stroke-width="1"/>'
        '<text x="0" y="%d" font-size="10" font-weight="700" fill="var(--text-2)">%d</text>'
        "%s</svg></div>"
        % (W, H, H, ", ".join(map(str, bars)), H - 18, W, H - 18,
           H - 18 - (H - 26), W, H - 18 - (H - 26), H - 24 - (H - 26) + 10, top, "".join(sv)),
        T)

    C["components/invoice.html"] = card(
        "Data", "Invoice row",
        "Reference numbers and amounts use tabular figures so they align down a "
        "column. Status is a labelled pill, never colour alone.",
        '<div style="width:340px;max-width:100%;display:flex;flex-direction:column;gap:10px">'
        + "".join('<div class="invrow"><div class="bd"><p class="no">%s</p>'
                  '<p class="who">%s</p></div><span class="tagp %s">%s</span>'
                  '<span class="amt">$%d</span></div>' % (no, who, c, st, amt)
                  for no, who, st, c, amt in
                  [("INV-1042", "D. Nguyen", "Paid", "ok", 180),
                   ("INV-1041", "A. Okafor", "Sent", "n", 240),
                   ("INV-1039", "M. Reyes", "Overdue", "w", 120)])
        + "</div>", T + "\n" + R(".invrow", ".tagp"))

    # -- Actions -----------------------------------------------------------
    C["components/buttons.html"] = card(
        "Actions", "Buttons and chips",
        "Every pressable scales to 0.96 on press - one value across the whole app. "
        "Primary clears 4.6:1 for white text; secondary carries a full-weight "
        "border rather than a tint.",
        '<div style="width:320px;max-width:100%;display:flex;flex-direction:column;gap:9px">'
        '<button class="btn pri">Choose this business</button>'
        '<button class="btn sec">Book a time</button>'
        '<button class="btn sec">Save</button></div>'
        '<p class="ds-note" style="margin-top:20px">Chips and slots</p>'
        '<div class="ds-row"><button class="chip on">Cleaning</button>'
        '<button class="chip">Rentals</button><button class="chip">Tutoring</button></div>'
        '<div class="ds-row" style="margin-top:10px"><button class="slot on">Wed</button>'
        '<button class="slot">Thu</button><button class="slot">11:30 AM</button></div>',
        T + "\n" + R(".btn", ".chip", ".slot"))

    return C


# ---------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "design-system"))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the bundle on disk is stale")
    a = ap.parse_args()

    css = style_block(io.open(APP, encoding="utf-8").read())
    imgs = {k: photo(k + ".jpg") for k in ("home", "clean", "clinic")}
    cards = build(css, imgs)

    stale = []
    for path, html in cards.items():
        full = os.path.join(a.out, path)
        old = io.open(full, encoding="utf-8").read() if os.path.exists(full) else None
        if old != html:
            stale.append(path)
        if not a.check:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            io.open(full, "w", encoding="utf-8").write(html)

    if a.check:
        if stale:
            print("design system is stale (%d): %s" % (len(stale), ", ".join(sorted(stale))))
            return 1
        print("design system is current (%d cards)" % len(cards))
        return 0

    print("wrote %d cards to %s" % (len(cards), a.out))
    if stale:
        print("changed: " + ", ".join(sorted(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
